# Generated by Django 4.0.2 on 2022-02-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FollowedUser', to='users.user')),
                ('followuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FollowUser', to='users.user')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
    ]
