# Generated by Django 4.0.2 on 2022-02-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='user_name',
            new_name='user',
        ),
    ]
