# Generated by Django 4.0.2 on 2022-02-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_username_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserName',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
